// eslint-disable-next-line import/no-anonymous-default-export
export default {
    companyName: 'NostalgiLog',
    comapnyDescription: "Welcome to NostalgiLog, where we bridge the gap between nostalgia and cutting-edge data analysis. Stepping into our digital time machine, we transport you back to the early days of the internet, capturing the essence of a bygone era when the world wide web was just beginning to take shape. Founded on a passion for preserving the digital history of yesteryears, NostalgiLog is dedicated to unraveling the mysteries and untold stories hidden within the vast archives of internet data.",
    lineDescription: 'Explore the digital footprints of the early internet era with our web traffic analysis for August 29 to August 30, 1995. This line chart visualizes the Requests per minute over the entire time span, providing insights into the browsing activity during this pivotal period in internet history. Journey back to the dawn of the world wide web and uncover trends, peaks, and patterns in user interactions as we delve into the virtual landscape of the mid-1990s.',
    lineTitle: 'Web Traffic Analysis: August 29-30, 1995',
    pieTitle: 'HTTP Response Code Distribution: August 29-30, 1995',
    pieDescription: 'Uncover the distribution of HTTP response codes during the period of August 29 to August 30, 1995, with this pie chart analysis. Explore the frequency of various HTTP response codes, including the ubiquitous 200 for successful requests, the elusive 404 for not found errors, the redirections denoted by 302, and more. Gain insights into the landscape of web interactions, from successful page retrievals to encounters with missing or redirected content, as we journey through the early days of the world wide web.',
    barDesciption: 'Explore the distribution of HTTP methods utilized during the period of August 29 to August 30, 1995, through this bar chart analysis. Gain insights into the variety of HTTP methods employed by web clients to interact with servers, including the common GET, POST, and HEAD methods, among others. Visualize the frequency of each method, shedding light on the diverse ways in which information was requested and exchanged in the early days of the internet. Dive into the digital archives and uncover the patterns of web interactions that shaped the landscape of the world wide web.',
    barTitle: 'HTTP Method Distribution: August 29-30, 1995',
    leteralBarDescription: 'Explore the distribution of response sizes for HTTP requests with response code 200 and a size less than 1000 bytes during the period of August 29 to August 30, 1995, with this lateral bar chart analysis. By grouping data into size ranges, this visualization provides insights into the distribution of response sizes, offering a comprehensive view of the content served by web servers during this time frame. Delve into the nuances of response sizes, from small informational payloads to larger content deliveries, as we navigate through the digital archives of the early internet era.',
    lateralBarTitle: 'Response Size Distribution (Code 200, Size < 1000B): August 29-30, 1995',
    aboutThis: 'About this',
    aboutThisDescription: 'This is a project created as a technical test for a job interview, MaterialUi and react95 have been used for its construction. The logs were collected by Laura Bottomley (laurab@ee.duke.edu) of Duke University.',
    repo: 'Repositiry'
}